export const DOCUMENT_REGISTRY = {
  AADHAAR: 'AADHAAR',
  PAN: 'PAN',
  GST_CERTIFICATE: 'GST_CERTIFICATE',
  UDYAM: 'UDYAM',
  CERTIFICATE_OF_INCORPORATION: 'CERTIFICATE_OF_INCORPORATION',
  BUSINESS_REGISTRATION: 'BUSINESS_REGISTRATION',
  PARTNERSHIP_DEED: 'PARTNERSHIP_DEED',
  LLP_AGREEMENT: 'LLP_AGREEMENT',
  MOA: 'MOA',
  AOA: 'AOA',
  ADDRESS_PROOF: 'ADDRESS_PROOF',
  RENT_AGREEMENT: 'RENT_AGREEMENT',
  LEASE_DEED: 'LEASE_DEED',
  PROPERTY_OWNERSHIP: 'PROPERTY_OWNERSHIP',
  PROPERTY_TAX: 'PROPERTY_TAX',
  FIRE_NOC: 'FIRE_NOC',
  FIRE_SAFETY_CERTIFICATE: 'FIRE_SAFETY_CERTIFICATE',
  FIRE_FIGHTING_LAYOUT: 'FIRE_FIGHTING_LAYOUT',
  ARCHITECTURAL_BUILDING_PLAN: 'ARCHITECTURAL_BUILDING_PLAN',
  STRUCTURAL_STABILITY_CERTIFICATE: 'STRUCTURAL_STABILITY_CERTIFICATE',
  FACTORY_LICENSE: 'FACTORY_LICENSE',
  POLLUTION_CONTROL_CONSENT: 'POLLUTION_CONTROL_CONSENT',
  ENVIRONMENTAL_CLEARANCE: 'ENVIRONMENTAL_CLEARANCE',
  FSSAI: 'FSSAI',
  LABOUR_LICENSE: 'LABOUR_LICENSE',
  SHOPS_ESTABLISHMENT: 'SHOPS_ESTABLISHMENT',
  TRADE_LICENSE: 'TRADE_LICENSE',
  LEGAL_METROLOGY: 'LEGAL_METROLOGY',
  IEC: 'IEC',
  BANK_STATEMENT: 'BANK_STATEMENT',
  CANCELLED_CHEQUE: 'CANCELLED_CHEQUE',
  SIGNBOARD_PHOTO: 'SIGNBOARD_PHOTO',
  AUTHORIZATION_LETTER: 'AUTHORIZATION_LETTER',
  BOARD_RESOLUTION: 'BOARD_RESOLUTION',
  CA_CERTIFICATE: 'CA_CERTIFICATE',
  FINANCIAL_STATEMENT: 'FINANCIAL_STATEMENT',
  PROJECT_REPORT: 'PROJECT_REPORT',
  ELECTRICAL_SAFETY_CERTIFICATE: 'ELECTRICAL_SAFETY_CERTIFICATE',
  OCCUPANCY_CERTIFICATE: 'OCCUPANCY_CERTIFICATE',
  COMPLETION_CERTIFICATE: 'COMPLETION_CERTIFICATE',
  BUILDING_PERMISSION: 'BUILDING_PERMISSION',
  LAND_CONVERSION: 'LAND_CONVERSION',
  MINING_PERMIT: 'MINING_PERMIT',
  DRUG_LICENSE: 'DRUG_LICENSE',
  MEDICAL_DEVICE_LICENSE: 'MEDICAL_DEVICE_LICENSE',
  TOURISM_REGISTRATION: 'TOURISM_REGISTRATION'
};

export function mapDisplayToRegistry(displayType) {
  const type = displayType.toLowerCase();
  
  if (type.includes('aadhaar')) return DOCUMENT_REGISTRY.AADHAAR;
  if (type.includes('pan')) return DOCUMENT_REGISTRY.PAN;
  if (type.includes('gst')) return DOCUMENT_REGISTRY.GST_CERTIFICATE;
  if (type.includes('udyam')) return DOCUMENT_REGISTRY.UDYAM;
  if (type.includes('incorporation')) return DOCUMENT_REGISTRY.CERTIFICATE_OF_INCORPORATION;
  if (type.includes('fire fighting') || type.includes('fire layout')) return DOCUMENT_REGISTRY.FIRE_FIGHTING_LAYOUT;
  if (type.includes('fire noc') || type.includes('fire safety')) return DOCUMENT_REGISTRY.FIRE_NOC;
  if (type.includes('architectural') || type.includes('building layout')) return DOCUMENT_REGISTRY.ARCHITECTURAL_BUILDING_PLAN;
  if (type.includes('structural')) return DOCUMENT_REGISTRY.STRUCTURAL_STABILITY_CERTIFICATE;
  if (type.includes('rent') || type.includes('lease')) return DOCUMENT_REGISTRY.RENT_AGREEMENT;
  if (type.includes('ownership') || type.includes('property')) return DOCUMENT_REGISTRY.PROPERTY_OWNERSHIP;
  if (type.includes('fssai')) return DOCUMENT_REGISTRY.FSSAI;
  if (type.includes('signboard')) return DOCUMENT_REGISTRY.SIGNBOARD_PHOTO;
  if (type.includes('bank') || type.includes('cheque')) return DOCUMENT_REGISTRY.BANK_STATEMENT;
  
  return null;
}
