/**
 * Prototype Demonstration Data for UDAAN Applicant Portal
 * Provides rich, realistic sample data for frontend prototype showcasing across all sections:
 * - Documents Vault
 * - Applications & Approvals
 * - Joint Inspections
 * - Matched Subsidy Schemes
 * - Grievance Tickets
 * - Notifications
 */

export const PROTOTYPE_DOCUMENTS = [
  {
    id: 101,
    document_type: 'Aadhaar Card',
    file_url: 'https://uidai.gov.in/sample_aadhaar.pdf',
    verified_status: 'verified',
    verified_at: '2026-09-02T10:15:00Z',
    uploaded_at: '2026-09-01T08:30:00Z',
    expiry_date: null,
    notes: 'Verified via DigiLocker UIDAI electronic API',
  },
  {
    id: 102,
    document_type: 'PAN Card',
    file_url: 'https://incometaxindia.gov.in/sample_pan.pdf',
    verified_status: 'verified',
    verified_at: '2026-09-02T10:18:00Z',
    uploaded_at: '2026-09-01T08:32:00Z',
    expiry_date: null,
    notes: 'PAN verified against NSDL real-time database',
  },
  {
    id: 103,
    document_type: 'Premises Rent Deed & Layout Plan',
    file_url: '/mock-docs/architectural-layout.html',
    verified_status: 'verified',
    verified_at: '2026-09-03T14:20:00Z',
    uploaded_at: '2026-09-02T11:45:00Z',
    expiry_date: '2028-08-31',
    notes: 'Commercial lease deed verified with Municipal registry (>15 sq. mtrs clear commercial area)',
  },
  {
    id: 104,
    document_type: 'Registered Pharmacist Registration Certificate',
    file_url: 'https://cdsco.gov.in/sample_pharmacist_reg.pdf',
    verified_status: 'verified',
    verified_at: '2026-09-03T16:05:00Z',
    uploaded_at: '2026-09-02T12:00:00Z',
    expiry_date: '2029-12-31',
    notes: 'State Pharmacy Council B.Pharm Registration valid and verified',
  },
  {
    id: 105,
    document_type: 'Refrigerator Invoice & Cold Chain Calibration Log',
    file_url: 'https://cdsco.gov.in/sample_cold_chain.pdf',
    verified_status: 'verified',
    verified_at: '2026-09-04T09:30:00Z',
    uploaded_at: '2026-09-03T15:20:00Z',
    expiry_date: null,
    notes: 'Commercial deep freezer 2°C - 8°C calibration report validated',
  },
  {
    id: 106,
    document_type: 'Fire Safety Layout & Architectural Drawing',
    file_url: '/mock-docs/fire-noc.html',
    verified_status: 'pending',
    verified_at: null,
    uploaded_at: '2026-09-05T14:10:00Z',
    expiry_date: null,
    notes: 'Under scrutiny by Divisional Fire Officer for Joint Inspection verification',
  },
  {
    id: 107,
    document_type: 'Structural Stability Certificate',
    file_url: '/mock-docs/structural-stability.html',
    verified_status: 'verified',
    verified_at: '2026-09-06T10:00:00Z',
    uploaded_at: '2026-09-06T09:00:00Z',
    expiry_date: null,
    notes: 'Certified by Chartered Structural Engineer (NBC 2016 compliant)',
  },
];

export const PROTOTYPE_APPLICATIONS = [
  {
    id: 201,
    approval_rule_id: 1,
    approval_name: 'Retail Drug License (Form 20 & 21)',
    department: 'State Food & Drug Administration (FDA / CDSCO)',
    status: 'pending_review',
    risk_level: 'medium',
    sla_days: 14,
    days_left: 5,
    sla_breached: false,
    hazard_level: 'moderate',
    submitted_at: '2026-09-02T10:30:00Z',
    requires_inspection: true,
  },
  {
    id: 202,
    approval_rule_id: 2,
    approval_name: 'Fire Safety Clearance (Provisional Fire NOC)',
    department: 'Fire & Emergency Services / Urban Administration',
    status: 'pending_inspection',
    risk_level: 'high',
    sla_days: 15,
    days_left: 6,
    sla_breached: false,
    hazard_level: 'high',
    submitted_at: '2026-09-02T10:30:00Z',
    requires_inspection: true,
  },
  {
    id: 203,
    approval_rule_id: 3,
    approval_name: 'Municipal Trade License (Gumasta Registration)',
    department: 'Municipal Corporation / Urban Local Bodies',
    status: 'auto_approved',
    risk_level: 'low',
    sla_days: 3,
    days_left: 0,
    sla_breached: false,
    hazard_level: 'low',
    submitted_at: '2026-09-02T10:30:00Z',
    requires_inspection: false,
  },
  {
    id: 204,
    approval_rule_id: 4,
    approval_name: 'Commercial GST & Professional Tax Enrollment',
    department: 'Commercial Tax Department / Goods & Services Tax Network',
    status: 'approved',
    risk_level: 'low',
    sla_days: 5,
    days_left: 0,
    sla_breached: false,
    hazard_level: 'low',
    submitted_at: '2026-09-01T11:00:00Z',
    requires_inspection: false,
  },
];

export const PROTOTYPE_INSPECTIONS = [
  {
    id: 301,
    status: 'scheduled',
    scheduled_date: '2026-09-12T11:30:00Z',
    result: null,
    notes: 'Joint Single-Window Inspection: Pharmacist presence, 2-8°C deep freeze temperature audit, and fire emergency exit egress compliance.',
    inspector_name: 'Dr. Rajeshwar Tiwari (Chief Drug Inspector, Zone 4) & S.K. Sharma (Fire Safety Officer)',
    applications: [
      { id: 201, approval_name: 'Retail Drug License (Form 20 & 21)', department: 'State FDA / CDSCO' },
      { id: 202, approval_name: 'Fire Safety Clearance (Fire NOC)', department: 'Fire & Emergency Services' },
    ],
  },
  {
    id: 302,
    status: 'completed',
    scheduled_date: '2026-08-28T14:00:00Z',
    result: 'pass',
    notes: 'Preliminary premises suitability inspection passed. Clear road access (>6m) and commercial power connectivity verified.',
    inspector_name: 'Anil Mehta (Municipal Revenue Inspector)',
    applications: [
      { id: 203, approval_name: 'Municipal Trade License (Gumasta)', department: 'Municipal Corporation' },
    ],
  },
];

export const PROTOTYPE_SCHEMES = [
  {
    id: 401,
    name: 'MP Capital Investment Subsidy Scheme 2026',
    description: 'Financial assistance offering 15% to 20% capital subsidy on equipment and infrastructure for newly registered enterprises.',
    benefit_description: 'Direct Benefit Transfer of up to ₹20,00,000 on approved fixed asset investments (refrigeration, dispensing racks & electricals).',
    sector: 'Pharma / Commercial',
    state: 'Madhya Pradesh',
    min_investment: 10,
    max_investment: 100,
    min_employees: 3,
  },
  {
    id: 402,
    name: 'Pradhan Mantri MUDRA Yojana (Tarun Category)',
    description: 'Government of India national credit guarantee scheme offering collateral-free institutional business loans for scaling enterprises.',
    benefit_description: 'Collateral-free working capital and term loan up to ₹10,00,000 at subsidized concession interest rates through partner public sector banks.',
    sector: 'All Priority Sectors',
    state: 'Pan India / MP',
    min_investment: 5,
    max_investment: 50,
    min_employees: 2,
  },
  {
    id: 403,
    name: 'MP Single Window 5% Interest Subvention Scheme',
    description: 'State government interest reimbursement program helping small enterprises lower financing overheads.',
    benefit_description: 'Annual 5% interest subvention reimbursed directly to enterprise bank account for 5 continuous operational years.',
    sector: 'Pharma / Healthcare / Services',
    state: 'Madhya Pradesh',
    min_investment: 15,
    max_investment: 200,
    min_employees: 4,
  },
  {
    id: 404,
    name: 'UDAAN Green Enterprise Clean Energy Grant',
    description: 'Special environmental incentive providing upfront subsidy for rooftop solar and energy-efficient cold chain machinery.',
    benefit_description: 'Up to ₹2,50,000 grant towards 5-star rated inverter cold storage equipment and solar back-up units.',
    sector: 'Commercial / Green Units',
    state: 'Madhya Pradesh',
    min_investment: 5,
    max_investment: 80,
    min_employees: 2,
  },
];

export const PROTOTYPE_GRIEVANCES = [
  {
    id: 501,
    ticket_number: 'GRV-2026-092',
    subject: 'Clarification on Retail Drug License Layout Approval & Partition Norms',
    description: 'Requested official clarification regarding whether a separate consultation cabin is mandatory for retail chemist counter under Form 20 norms.',
    priority: 'medium',
    status: 'resolved',
    department: 'State Food & Drug Administration (FDA)',
    created_at: '2026-09-03T11:20:00Z',
    updated_at: '2026-09-04T16:45:00Z',
    resolution_notes: 'Clarification issued: As per State Drug Rules Rule 64, standard retail pharmacy require only minimum 10 sq. meters partitioned storage space; separate doctor consultation cabin is optional for pure retail sales.',
  },
  {
    id: 502,
    ticket_number: 'GRV-2026-114',
    subject: 'Request to Coordinate Fire NOC Site Visit with Drug Inspector',
    description: 'Applicant requested combining the individual departmental visits into a single time window to avoid multiple facility shutdowns.',
    priority: 'high',
    status: 'in_progress',
    department: 'Fire & Emergency Services / Single Window Desk',
    created_at: '2026-09-05T09:15:00Z',
    updated_at: '2026-09-05T14:30:00Z',
    resolution_notes: 'Desk Officer routed request to Single Window Joint Cell. Inspection has been successfully consolidated into Joint Inspection JIT-2026-881 for 12 Sept 2026.',
  },
];

export const PROTOTYPE_NOTIFICATIONS = [
  {
    id: 601,
    type: 'inspection_scheduled',
    title: 'Joint Site Inspection Scheduled',
    message: 'Joint Single-Window Site Visit JIT-2026-881 has been scheduled for 12 Sept 2026 at 11:30 AM. Lead: Dr. Rajeshwar Tiwari (FDA) & S.K. Sharma (Fire Dept).',
    is_read: false,
    created_at: '2026-09-05T15:00:00Z',
  },
  {
    id: 602,
    type: 'application_update',
    title: 'Document Verified: Premises Rent Deed & Blueprint',
    message: 'Your commercial premises lease deed has been validated by Urban Administration Scrutiny Officers.',
    is_read: false,
    created_at: '2026-09-03T14:25:00Z',
  },
  {
    id: 603,
    type: 'application_update',
    title: 'Municipal Trade License Auto-Approved',
    message: 'Your Municipal Trade License (Gumasta) has been auto-approved under EoDB low-risk self-certification rules. Certificate is available for download.',
    is_read: true,
    created_at: '2026-09-02T10:35:00Z',
  },
  {
    id: 604,
    type: 'sla_warning',
    title: 'SLA Milestone: Retail Drug License Under Review',
    message: 'State FDA Scrutiny Officer has completed document audit. Joint inspection report expected within 5 working days.',
    is_read: true,
    created_at: '2026-09-04T09:00:00Z',
  },
  {
    id: 605,
    type: 'scheme_recommendation',
    title: 'New Scheme Matched: MP Capital Subsidy',
    message: 'Your business profile is eligible for up to ₹20,00,000 in capital equipment subsidies under the 2026 policy.',
    is_read: true,
    created_at: '2026-09-01T12:00:00Z',
  },
];
